# Generated by Django 5.0 on 2025-10-25 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='class_recordings/')),
                ('recording_link', models.URLField(blank=True, help_text='External link (e.g., YouTube)', null=True)),
                ('date_recorded', models.DateField()),
                ('duration', models.CharField(help_text='e.g., 1h 30m', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='courses.courseallocation')),
            ],
            options={
                'verbose_name': 'Class Recording',
                'verbose_name_plural': 'Class Recordings',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.JSONField(help_text='Whiteboard drawing data in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboards', to='courses.courseallocation')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboards', to='academics.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboards', to='academics.session')),
            ],
            options={
                'verbose_name': 'Whiteboard',
                'verbose_name_plural': 'Whiteboards',
                'ordering': ['-updated_at'],
            },
        ),
    ]
