# Generated by Django 5.0 on 2025-10-25 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmittedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jamb_registration_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('course_codes', models.TextField(help_text='Comma-separated course codes')),
                ('admission_pin', models.CharField(editable=False, max_length=20, unique=True)),
                ('admission_status', models.CharField(choices=[('pending', 'Pending Registration'), ('completed', 'Registration Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='academics.session')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='academics.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='academics.program')),
            ],
            options={
                'verbose_name': 'Admitted Student',
                'verbose_name_plural': 'Admitted Students',
                'ordering': ['-created_at'],
                'permissions': [('can_verify_student_admission', 'Can verify student admission'), ('can_upload_admitted_students', 'Can upload admitted students')],
            },
        ),
    ]
