# Generated by Django 5.0 on 2025-10-25 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_password_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Change Request',
                'verbose_name_plural': 'Password Change Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('designation', models.CharField(help_text='e.g., Lecturer I, Lecturer II, HOD, Dean', max_length=50)),
                ('date_of_employment', models.DateField()),
                ('qualifications', models.TextField(blank=True, help_text='Academic qualifications')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'permissions': [('can_upload_materials', 'Can upload course materials'), ('can_create_assignments', 'Can create assignments'), ('can_grade_assignments', 'Can grade assignments'), ('can_mark_attendance', 'Can mark attendance'), ('can_submit_results', 'Can submit results'), ('can_record_classes', 'Can record classes'), ('can_use_whiteboard', 'Can use whiteboard'), ('can_view_allocated_courses', 'Can view allocated courses'), ('can_view_course_students', 'Can view course students'), ('can_allocate_courses', 'Can allocate courses')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('jamb_registration_number', models.CharField(max_length=20, unique=True)),
                ('admission_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('admitted', 'Admitted'), ('graduated', 'Graduated')], default='pending', max_length=20)),
                ('has_paid_registration_fee', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('admission_letter', models.FileField(blank=True, null=True, upload_to='admission_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admitted_students', to='academics.session')),
                ('current_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.level')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'permissions': [('can_view_own_profile', 'Can view own profile'), ('can_register_courses', 'Can register courses'), ('can_view_materials', 'Can view materials'), ('can_submit_assignments', 'Can submit assignments'), ('can_view_results', 'Can view results'), ('can_view_attendance', 'Can view attendance'), ('can_request_password_change', 'Can request password change')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('student', 'Student')], default='student', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
