# Generated by Django 5.0 on 2025-10-25 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='College of Education', max_length=200)),
                ('school_address', models.TextField(blank=True)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('school_phone', models.CharField(blank=True, max_length=15)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('school_website', models.URLField(blank=True)),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('established_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Information',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('matric_number_format', models.CharField(default='COE/{YEAR}/{DEPT}/{SERIAL}', help_text='Use {YEAR}, {DEPT}, {SERIAL} as placeholders', max_length=100)),
                ('staff_id_format', models.CharField(default='STAFF/{YEAR}/{SERIAL}', help_text='Use {YEAR}, {SERIAL} as placeholders', max_length=100)),
                ('allow_student_registration', models.BooleanField(default=True, help_text='Toggle student admission registration')),
                ('allow_course_registration', models.BooleanField(default=True, help_text='Toggle course registration')),
                ('jamb_verification_enabled', models.BooleanField(default=True)),
                ('paystack_public_key', models.CharField(blank=True, max_length=200)),
                ('paystack_secret_key', models.CharField(blank=True, max_length=200)),
                ('current_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_current_semester', to='academics.semester')),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_current_session', to='academics.session')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'permissions': [('can_manage_school_info', 'Can manage school information'), ('can_manage_system_settings', 'Can manage system settings')],
            },
        ),
    ]
